MillennialResortManager/MillennialResortWebSite/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using DataObjects;

namespace MillennialResortWebSite.Models
{
    /// <summary>
    /// Added by Matt H. on 4/18/19
    /// View Model class for Contact Us page.
    /// </summary>
    public class ContactViewModel
    {
        [Required]
        [Display(Name = "First Name")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "First Name must be at least 2 characters in length")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Last Name must be at least 2 characters in length")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Message to Send")]
        [MinLength(20, ErrorMessage = "Your Message must be at least 20 characters in length.")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Email")]
        [StringLength(255, MinimumLength = 15, ErrorMessage = "The Email entered must be at least 15 characters in length")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "You must select a Subject Header from the drop-down list")]
        [Display(Name = "Subject Header")]
        public string SelectedSubject { get; set; }

        public IEnumerable<SelectListItem> Subjects { get; set; }
    }

    /// <summary>
    /// Added by Matt H. on 4/18/19
    /// View Model class for index page's mailing list form.
    /// </summary>
    public class IndexPageMailingListViewModel
    {
        [Required]
        [Display(Name = "First Name")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "First Name must be 2 or more characters")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Last Name must be 2 or more characters")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Email")]
        [StringLength(255, MinimumLength = 15, ErrorMessage = "Email must be at least 15 characters in length")]
        public string Email { get; set; }

    }

    /// <summary>
    /// Added by Matt H. on 4/18/19
    /// View Model class comprised of both Reservation View Model and MailingList View Model
    /// for the index page.
    /// </summary>
    public class HomeViewModelsMixer
    {
        /*public List<IndexPageMailingListViewModel> MailingLists { get; set; } */

        public ReservationSearchModel Reservation { get; set; }

        public IndexPageMailingListViewModel MailingList { get; set; } 


       

    }
}

MillennialResortManager/MillennialResortWebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataObjects;
using MillennialResortWebSite.Models;
using System.Net.Mail;

namespace MillennialResortWebSite.Controllers
{
    public class HomeController : Controller
    {

        


        /// <summary>
        /// Added by Matt H. on 4/18/19
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            HomeViewModelsMixer homeViewModelsMixer = new HomeViewModelsMixer();

            homeViewModelsMixer.Reservation = new ReservationSearchModel();

            homeViewModelsMixer.MailingList = new IndexPageMailingListViewModel();

            return View(homeViewModelsMixer);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        /// <summary>
        /// Added by Matt H. on 4/18/19
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MailingList(HomeViewModelsMixer homeViewModelsMixer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    EMailer.EmailUsername = "millennialcontact107@gmail.com";
                    EMailer.EmailPassword = "Supportteam1";

                    EMailer eMailer = new EMailer
                    {
                        ToEmail = homeViewModelsMixer.MailingList.Email,
                        Subject = homeViewModelsMixer.MailingList.FirstName + " "
                                    + homeViewModelsMixer.MailingList.LastName
                                    + " - Subscription to Our Monthly News Letter",
                        Body = "Thank you " + homeViewModelsMixer.MailingList.FirstName
                                    + " for signing up for our mailing list. You will now receive monthly "
                                    + "reports regarding all that is happening with the resort, including any pressing "
                                    + "issues or updates, as well as details regarding special events. "
                                    + "Please note: to opt out of our mailing list at any time, reply with the words OPT OUT",
                        IsHtml = true
                    };
                    eMailer.Send();
                    ViewBag.ResultStatus = "SignupSuccess";
                    ViewBag.FormSubmitResult = "Success! You're now signed up, check your inbox.";
                    return View("ContactResult");
                }
                catch (SmtpException smtpEx)
                {
                    ViewBag.ResultStatus = "Error";
                    //ViewBag.FormSubmitResult = "ERROR: invalid email address.";

                    ViewBag.FormSubmitResult = "ERROR: invalid email address.";
                    return View("ContactResult");
                    //return Content(smtpEx.Message); <---  for smtpException error-testing
                }
            }
            else
            {

                return View(homeViewModelsMixer);
            }
        }

        /// <summary>
        /// Added by Matt H. on 4/18/19
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            ContactViewModel contactViewModel = new ContactViewModel();
            contactViewModel.SelectedSubject = "";
            contactViewModel.Subjects = new List<SelectListItem>()
            {

                new SelectListItem
              {
                  Text = "--Select a Value--",
                  Value = "placeholder",
                  Disabled = true,
              },
              new SelectListItem
              {
                  Text = "Current Member - Report Issue",
                  Value = "Current Member/Guest - Reporting an issue"
              },
              new SelectListItem
              {
                  Text = "Previous Member - Report Issue",
                  Value = "Previous Member/Guest - Reporting an issue"
              },
              new SelectListItem
              {
                  Text = "Questions about pricing",
                  Value = "Questions about pricing"
              },
              new SelectListItem
              {
                  Text = "Questions about reservations",
                  Value = "Questions about reservations"
              },
              new SelectListItem
              {
                  Text = "Questions about an event",
                  Value = "Questions about an event"
              },
              new SelectListItem
              {
                  Text = "Questions about pets",
                  Value = "Questions about pets"
              },
              new SelectListItem
              {
                  Text = "Questions about jobs",
                  Value = "Questions about job opportunities at the resort"
              },
              new SelectListItem
              {
                  Text = "MISC/OTHER",
                  Value = "MISC/OTHER"
              },
            };

            return View(contactViewModel);
        }

        /// <summary>
        /// Added by Matt H. on 4/18/19
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactViewModel contactViewModel)
        {
            if (!contactViewModel.SelectedSubject.Equals("placeholder") && ModelState.IsValid)
            {
                try
                {
                    EMailer.EmailUsername = contactViewModel.Email;
                    EMailer.EmailPassword = "Supportteam1";

                    EMailer eMailer = new EMailer
                    {
                        ToEmail = "millennialcontact107@gmail.com",
                        Subject = contactViewModel.FirstName + " " + contactViewModel.LastName + " - " + contactViewModel.SelectedSubject,
                        Body = contactViewModel.Description,
                        IsHtml = true
                    };
                    eMailer.Send();
                    ViewBag.ResultStatus = "Success";
                    ViewBag.FormSubmitResult = "Success! Email sent.";
                    return View("ContactResult");
                }
                catch (SmtpException smtpEx)
                {
                    ViewBag.ResultStatus = "Error";
                    ViewBag.FormSubmitResult = "ERROR: invalid email address.";
                    return View("ContactResult");
                }
            }
            else
            {
                if (contactViewModel.SelectedSubject.Equals("placeholder"))
                {
                    ViewBag.DropdownError = "You must select an option from the drop down.";
                }
                else
                {
                    ViewBag.DropdownError = "";
                }


                contactViewModel.Subjects = new List<SelectListItem>()
            {
              new SelectListItem
              {
                  Text = "--Select a Values--",
                  Value = "placeholder",
                  Disabled = true,
              },
              new SelectListItem
              {
                  Text = "Current Member - Report Issue",
                  Value = "Current Member/Guest - Reporting an issue"
              },
              new SelectListItem
              {
                  Text = "Previous Member - Report Issue",
                  Value = "Previous Member/Guest - Reporting an issue"
              },
              new SelectListItem
              {
                  Text = "Questions about pricing",
                  Value = "Questions about pricing"
              },
              new SelectListItem
              {
                  Text = "Questions about reservations",
                  Value = "Questions about reservations"
              },
              new SelectListItem
              {
                  Text = "Questions about an event",
                  Value = "Questions about an event"
              },
              new SelectListItem
              {
                  Text = "Questions about pets",
                  Value = "Questions about pets"
              },
              new SelectListItem
              {
                  Text = "Questions about jobs",
                  Value = "Questions about job opportunities at the resort"
              },
              new SelectListItem
              {
                  Text = "MISC/OTHER",
                  Value = "MISC/OTHER"
              },
            };

                return View(contactViewModel);
                //return RedirectToAction("Contact");
            }

        }

        public ActionResult Rooms()
        {
            ViewBag.Message = "Rooms Page";

            return View();
        }






    }
}

MillennialResortManager/MillennialResortWebSite/Controllers/RoomsController.cs
using DataAccessLayer;
using DataObjects;
using LogicLayer;
using MillennialResortWebSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MillennialResortWebSite.Controllers
{
    public class RoomsController : Controller
    {
        IRoomManager roomManager = new RoomManager();

        IReservationManager reservationManager = new ReservationManagerMSSQL();

        IGuestManager _guestManager = new GuestManager();

        IRoomType _roomType = new RoomTypeManager();

        IEnumerable<String> _types = null;


        // GET: Rooms
        public ActionResult Index(ReservationSearchModel model)
        {
            _types = _roomType.RetrieveAllRoomTypes();
            roomManager = new RoomManager();

            model.Rooms = roomManager.RetrieveRoomList();

            int hour = DateTime.Now.Hour;

            ViewBag.Greeting = hour < 12 ? "Good Morning" : "Good Afternoon";
            ViewBag.Types = _types;
            return View(model);

        }





        [Authorize]
        public ActionResult Create(int id, DateTime start, DateTime end, int numGuest)
        {
            _types = _roomType.RetrieveAllRoomTypes();
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            Room room = null;
            Guest guest = new Guest();
            try
            {
                room = roomManager.RetreieveRoomByID(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            try
            {
                string email = User.Identity.Name;
                guest = _guestManager.RetrieveGuestByEmail(email);
            }
            catch
            {
                return RedirectToAction("Login", "Account");
            }


            NewReservation res = new NewReservation()
            {
                ArrivalDate = start,
                DepartureDate = end,
                NumberOfGuests = numGuest,
                numberOfPets = 0,
                RoomType = room.RoomType,
                Notes = ""
            };

            ViewBag.Types = _types;
            return View(res);
        }


        // POST: Reservaion/Create
        [HttpPost]
        public ActionResult Create(NewReservation reservation)
        {
            _types = _roomType.RetrieveAllRoomTypes();
            if (ModelState.IsValid)
            {
                try
                {

                    Guest guest = new Guest();
                    string email = User.Identity.Name;
                    guest = _guestManager.RetrieveGuestByEmail(email);
                    Reservation res = new Reservation()
                    {
                        MemberID = guest.MemberID,
                        NumberOfGuests = reservation.NumberOfGuests,
                        ArrivalDate = reservation.ArrivalDate.Value,
                        DepartureDate = reservation.DepartureDate.Value,
                        Notes = reservation.Notes
                    };
                    if (reservationManager.AddReservation(res))
                    {
                        return RedirectToAction("Index", "MyAccount");
                    }
                }
                catch
                {
                    throw;
                }
            }

            ViewBag.Types = _types;
            return View(reservation);
        }

    }
}

MillennialResortManager/MillennialResortWebSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<html>
<head>
    <script>
        var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }
    </script>




    <style>
        
        img {
            float: left;
        }

        div.a {
            font-family: Impact, 'Arial Narrow Bold', sans-serif;
            font-size: x-large;
            text-align: center;
        }

        div.b {
            text-align: left;
            font-size: small;
        }

        h2.a {
            text-decoration: underline;
            color: chocolate;
            font-family: cursive;
        }

        h2.b {
            text-decoration: underline;
            color: blue;
            font-family: cursive;
        }

        h2.c {
            text-decoration: underline;
            color: black;
            font-family: cursive;
        }

        h1 {
            
            color: slategrey;
            text-align: left;
            font-family: sans-serif
        }

        div.gallery {
            border: 1px solid #ccc;
        }

            div.gallery:hover {
                border: 1px solid #777;
            }

            div.gallery img {
                width: 100%;
                height: auto;
            }

        div.desc {
            padding: 15px;
            text-align: center;
        }

        * {
            box-sizing: border-box;
        }

        .post-body img {
            display: block;
        }

        .responsive {
            padding: 0 6px;
            float: left;
            width: 24.99999%;
        }

        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }
       
     .ulpage {
            font-size:24px;
        }
    </style>

</head>
<body>

    <div class="jumbotron jumbotronBackGround">
        <div class="container body-content">

            <h1 style="text-align:center">About Our Hotel</h1>
            <div class="container">

            </div>
            <div class="b">
                <p>
                    <img src="~/Content/images/hotel/Pool-01.jpg" alt="Trulli" style="width:500px;  box-shadow: 5px 5px 10px; height:300px; margin-right:40px; font-family:Arial; font-size:medium; border-radius:15px;">
                </p>
                <p style="color:white;  text-shadow: 2px 2px 5px black; font-size: 24px;">
                    <br />
                    Each room in the Millennial Resorts & Spa is inspired by music and memories. As you enter through the hand-carved door,
                    each room reflects a global heritage, with distressed hardwood floors, Moroccan rugs, mahogany furniture and brightly-colored mosaic
                    tiles. Our luxury rooms and suites are designed to meet your every need. Natural Mystic Spa is just what you need. Choose from a menu
                    of exhilarating excursions to feed your explorative soul. Whether snorkeling in the warm waters or lounging by our pools, you will be in pure paradise bliss.
                    Every Millennial Resorts sits directly on a stunning beach or land, on many of the most gorgeous islands in a region famous for its exquisite azure waters with
                    the best luxury all-inclusive experience. Make Millennial Resorts your next vacation destination.
                    <br />

                </p>
            </div>

            <br />
        </div>


        <br />
        <br />




    </div>
    <div class="wrapper row2">
        <div id="container" class="clear">

            <div id="about-us" class="clear">



                <div class="jumbotron jumbotronEvents">
                    <div class="a">
                        <span style=" margin-right:50px;">
                            <br />
                            Millennial Resort offers a number of facilities and conveniences.<p>@Html.ActionLink("Make A Reservation Now", "Index", "Rooms")</p>

                        </span>

                    </div> <br />
                    <br />
                    <div class="container">
                        <h1>FACILITIES</h1>
                        <ul class="ulpage">
                            <li>Pool deck swimming pool</li>
                            <li>Hair Salon</li>
                            <li>Fitness Center.</li>
                            <li>Bar.</li>
                            <li>Parking space.</li>

                            <li>Free WiFi in meeting rooms, lobby and restaurants.</li>
                            <li>Laundry and Valet service</li>


                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="jumbotron jumbotronHighlights">
        <div class="container body-content">
            <h1> Coming Soon in 2020! </h1>
            <div class="responsive">
                <div class="gallery">

                    <a target="_blank" href="~/Content/images/hotel/03-RIVUE.jpg">
                        <img src="~/Content/images/hotel/03-RIVUE.jpg" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>
            <div class="responsive">
                <div class="gallery">

                    <a target="_blank" href="~/Content/images/hotel/02-RIVUE.jpg">
                        <img src="~/Content/images/hotel/02-RIVUE.jpg" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>



            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="~/Content/images/The new/13.jpg">
                        <img src="~/Content/images/The new/13.jpg" alt="Room" width="600" height="400">
                    </a>


                </div>
            </div>

            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="~/Content/images/The new/15.jpg">
                        <img src="~/Content/images/The new/15.jpg" alt="Cinque Terre" width="600" height="400"><br /><br />
                    </a>

                </div>
            </div>






            <h1>New Island Hotel</h1>





            <div class="responsive">
                <div class="gallery">

                    <a target="_blank" href="~/Content/images/hotel/05-Waterfront-Balcony.jpg">
                        <img src="~/Content/images/hotel/05-Waterfront-Balcony.jpg" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>

            <div class="responsive">
                <div class="gallery">

                    <a target="_blank" href="~/Content/images/hotel/07-TheConservatory.jpg">
                        <img src="~/Content/images/hotel/07-TheConservatory.jpg" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>

            <div class="responsive">
                <div class="gallery">

                    <a target="_blank" href="~/Content/images/hotel/down1interior-1-edit.jpg">
                        <img src="~/Content/images/hotel/down1interior-1-edit.jpg" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>

            <div class="responsive">
                <div class="gallery">

                    <a target="_blank" href="~/Content/images/hotel/RIVUE-West-Wheel-with-Red-Roses.JPG">
                        <img src="~/Content/images/hotel/RIVUE-West-Wheel-with-Red-Roses.JPG" alt="Cinque Terre" width="600" height="400"><br /><br />
                        <br />
                    </a>
                </div>
            </div>




            <h1> Weddings at the Resort </h1>



            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="~/Content/images/wedding/286A7461.JPG">
                        <img src="~/Content/images/wedding/286A7461.JPG" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>





            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="~/Content/images/wedding/386.JPG">
                        <img src="~/Content/images/wedding/386.JPG" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>

            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="~/Content/images/wedding/dhar_0853.JPG">
                        <img src="~/Content/images/wedding/dhar_0853.JPG" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>
            </div>



            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="~/Content/images/wedding/wedding-brides2LG.jpg">
                        <img src="~/Content/images/wedding/wedding-brides2LG.jpg" alt="Cinque Terre" width="600" height="400">
                    </a>
                </div>

            </div>

        </div>
    </div>

    <div class="jumbotron jumbotronEvents">
        <div class="container">
            <h2>Resort Events</h2>
            <div class="col-sm-6">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">

                        <div class="item active">
                            <img src="~/Content/images/eventSlider/hawaii-surfboards.jpg" alt="Surf Boards">
                        </div>

                        <div class="item">
                            <img src="~/Content/images/eventSlider/market.jpg" alt="Market">
                        </div>

                        <div class="item">
                            <img src="~/Content/images/eventSlider/redrocks.jpg" alt="Concert">
                        </div>

                        <div class="item">
                            <img src="~/Content/images/eventSlider/snorkelling-bali.jpg" alt="Snorkeling">
                        </div>
                    </div>

                    <!-- Left and right controls -->

                </div>
            </div>

            <div class="col-sm-6">
                <div class="eventsText">
                    <h1>Surf, Swim, Music Festivals, Bike, Hike, Markets and More!</h1>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

MillennialResortManager/MillennialResortWebSite/Views/Home/ContactResult.cshtml
@{
    ViewBag.Title = ViewBag.FormSubmitResult;
}

@if (ViewBag.ResultStatus == "Success")
{
    <h1>@ViewBag.FormSubmitResult</h1>
    <br />
    <p>Your Email has been sent. A member of support will get back to you prompty.</p>
}

@if (ViewBag.ResultStatus == "Error")
{
    <h1>@ViewBag.FormSubmitResult</h1>
    <br />
    <p>The Email entered was not a valid gmail address. Please go back to the contact page, and try again.</p>
}

@if (ViewBag.ResultStatus == "SignupSuccess")
{
    <h1>@ViewBag.FormSubmitResult</h1>
    <br />
    <p>Thank you for signing up to recieve our newsletter. Please check your inbox for a confirmation letter.</p>
}

@if (ViewBag.ResultStatus == "SignupError")
{
    <h1>@ViewBag.FormSubmitResult</h1>
    <br />
    <p>The Email entered was not a valid gmail address. Please go back to the contact page, and try again.</p>
}

MillennialResortManager/MillennialResortWebSite/Views/Home/View.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

MillennialResortManager/MillennialResortWebSite/Views/Home/_ReservationSearch.cshtml
@model MillennialResortWebSite.Models.ReservationSearchModel

@using (Html.BeginForm("Index", "Rooms"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal planTripHomepage">
    <h2>Plan Your Vacation</h2>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">

        <div class="col-md-10">


            @Html.EditorFor(model => model.ArrivalDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Start Date", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.ArrivalDate, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">

        <div class="col-md-10">


            @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control", placeholder = "End Date", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-10">
          
            @Html.DropDownListFor(model => model.NumberOfGuests, Enumerable.Range(1, 25).Select(i => new SelectListItem { Text = i.ToString() + " Guest", Value = i.ToString() }),
                                    new { @class = "form-control Sleeps" })

            @Html.ValidationMessageFor(model => model.NumberOfGuests, "", new { @class = "text-danger" })

          


        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" id="centerButton" class="btn btn-default" />
        </div>
    </div>

    <p>@Html.ActionLink("View all Properties", "Index", "Rooms")</p>

</div>
}