MillennialResortManager/MillennialResortWebSite/Controllers/BuildingController.cs
using DataAccessLayer;
using DataObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MillennialResortWebSite.Controllers
{
    public class BuildingController : Controller
    {
        IBuildingAccessor buildingAccessor = new BuildingAccessorMock();
        // GET: Building
        public ActionResult Index()
        {
            List<Building> buildings = buildingAccessor.SelectAllBuildings();

            return View(buildings);
        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            Building building = buildingAccessor.SelectBuildingByID(id);
            return View(building);
        }
    }
}

MillennialResortManager/MillennialResortWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Fugaz+One" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
  


</head>
<body>

    <div class="top-container">
        <div class="mobileHide"> @Html.Partial("_LoginPartial")</div>
       
    </div>
    @*<marquee>
            <p>Welcome to Millenial Resorts! Enjoy the endless summer at anyone of our resorts located globally, accross the Millenial Verse.</p>
        </marquee>*@






    <div class="resortHeader" id="myHeader">

        <header class="clearfix">

            <div class="navbar-inverse navbar-default">



                @*<div class="container">*@

                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <div class="navbar-collapse collapse navbar-display">

                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Home", "Index", "Home")</li>

                        <li>@Html.ActionLink("Rooms", "Rooms", "Home")</li>

                        <li>@Html.ActionLink("Amenities", "Index", "Amenities")</li>

                        <li>@Html.ActionLink("Events", "Index", "Event")</li>

                        <li>@Html.ActionLink("Venues", "Index", "Building")</li>
                        

                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("My Account", "Index", "MyAccount")</li>
                        }









                    </ul>
                    @*@Html.ActionLink("MILLENIAL RESORTS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                    <div class="mobileShow">@Html.Partial("_LoginPartial")</div>

                    

                </div>

            </div>
            @*</div>*@

        </header>

    </div>










    @RenderBody()



    <footer class="footerBackground">

        <div class="footer-widgets">

            <div class="container">

                <div class="col-md-6 col-lg-3">
                    <div class="footer-widget" id="">
                        <h3>LATEST NEWS</h3>
                        <div class="inner">
                            <ul class="latest-posts">
                                <li>
                                    <a href="/">Home</a>
                                </li>
                                <li>
                                    <a href="/content/rooms.aspx">Rooms</a>
                                </li>
                                <li>
                                    <a href="/content/gallery.aspx">Gallery</a>
                                </li>
                                <li>
                                    <a href="/content/history.aspx">History</a>
                                </li>
                                <li>
                                    @Html.ActionLink("Accounts Payable", "Index", "PayablesTest")
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="footer-widget" id="">
                        <h3>EVENTS</h3>
                        <div class="inner">
                            <ul class="latest-posts">
                                <li>
                                    <a href="/">Today's Events</a>
                                </li>
                                <li>
                                    <a href="/content/rooms.aspx">Resort Events</a>
                                </li>
                                <li>
                                    <a href="/content/gallery.aspx">Local Events</a>
                                </li>
                                <li>
                                    <a href="/content/history.aspx">Night Life</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="footer-widget" id="">
                        <h3>ROOMS</h3>
                        <div class="inner">
                            <ul class="latest-posts">
                                <li>
                                    <a href="/">Hotel Hostel</a>
                                </li>
                                <li>
                                    <a href="/content/rooms.aspx">Single Suite</a>
                                </li>
                                <li>
                                    <a href="/content/gallery.aspx">Double Suite</a>
                                </li>
                                <li>
                                    <a href="/content/history.aspx">Executive Suite</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="footer-widget" id="">
                        <h3>PETS</h3>
                        <div class="inner">

                            <ul class="latest-posts">
                                <li>
                                    @*<a href="/">Pets</a>*@ @Html.ActionLink("Pets", "Index", "DeveloperPage")
                                </li>
                                <li>
                                    <a href="/content/rooms.aspx">Pet Policy</a>
                                </li>
                                <li>
                                    <a href="/content/gallery.aspx">Pet Events</a>
                                </li>
                                <li>
                                    <a href="/content/history.aspx">Pet Pics</a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>

            </div>

        </div>

        <div class="col-md-12 col-md-offset-5 footerDate">
            <p>&copy; @DateTime.Now.Year - Welcome to Millennial Resorts</p>
        </div>
    </footer>






    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/main")






</body>
</html>

MillennialResortManager/MillennialResortWebSite/Views/Shared/_LayoutPayable.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/knockout-3.0.0.js"></script>
    @RenderSection("Scripts")
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>